services:
  site:
    build:
      context: .
    init: true
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    working_dir: /srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      HOME: /tmp
      JEKYLL_ENV: development
    volumes:
      - .:/srv/jekyll
