#!/bin/sh

set -eu

if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose is required to run the dev server." >&2
  exit 1
fi

export DOCKER_UID="$(id -u)"
export DOCKER_GID="$(id -g)"
export RUBY_VERSION="$(tr -d '\n' < .ruby-version)"
RUBY_VERSION="${RUBY_VERSION#ruby-}"
export RUBY_VERSION

exec docker compose up --build site
